name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAME: php-fpm-mysqli
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF##*/} .
    - name: Login GPR
      run: |
        docker login -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN} ghcr.io
    - name: Push Docker image
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF##*/}
