name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    env:
      IMAGE_NAME: php-fpm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${GITHUB_REF##*/} .
    - name: Login GHCR
      run: |
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${GITHUB_REF##*/}
